### PR TITLE
corrected contacts.json format

### PR DESCRIPTION
**Pull request by kstoops815**

### CODE REVIEW

**Comment by rousell** [comment]
@kstoops815 these changes look good! the only additional thing I'm going to have you do is to change the uids in your seed file to real uids that are registered by your application. For testing purposes, you will want to seed at least a couple with the uid that gets generated from your google account. 

Let me know if you have any questions!

**Comment by kstoops815** [comment]
Thank you Lauren!  I pushed up the changes. I believe I have done it correctly. If not, let me know!

**Comment by rousell** [comment]
@kstoops815 The changes you made look good! However, I would like you to put in a valid uid for the contacts that still are using a dummy uid. For this, you can use the uid that I registered with for your application: aSAiSfi9kGU3iVB8qtsOlBSaTHq2

**Comment by kstoops815** [comment]
@rousell I updated those uids.  If I am understanding correctly, I should have my valid uid in some (which I put that in the first 5 contacts), and then your valid uid in the last 5.  Hopefully I am understanding this correctly. Thank you!

**Comment by morecallan** [comment]
👍 🥇

**Pull request merged**
